# server 변수 설정
@server = http://localhost:3000

### 게시판 리스트 GET 요청 보내기
GET {{server}}/board

### 게시글 등록 POST 요청 보내기
POST {{server}}/board/create
Content-Type: application/json

{
  "title": "게시판 이용안내",
  "content": "ㅁㄴㅇㄹㅂㅈㄷㄹㅁㄴㅇㄹㅁㅈㄷㄹ"
}

### 사용자 등록 POST 요청 보내기
POST {{server}}/users/register
Content-Type: application/json

{
    "username": "manager1",
    "email": "manager1@example.com",
    "password": "manager1!",
    "role": "manager"
}