# server 변수 설정
@server = http://localhost:3000

### 게시판 리스트 GET 요청 보내기
GET {{server}}/board

### 게시글 등록 POST 요청 보내기
POST {{server}}/board
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWEzM2Y0Y2M3NDU1NTAzMDdjNjMxNCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzI5Nzc1MjU3LCJleHAiOjE3Mjk3Nzg4NTd9.4k85dM0JR_NguHz0FdlN_ZiEnIXbixx7i7SuFYVwN1A
Content-Type: application/json

{
  "title": "로그인 후 게시글 등록 테스트",
  "content": "Token 발급받았음 <br/> accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWEzM2Y0Y2M3NDU1NTAzMDdjNjMxNCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzI5Nzc1MjU3LCJleHAiOjE3Mjk3Nzg4NTd9.4k85dM0JR_NguHz0FdlN_ZiEnIXbixx7i7SuFYVwN1A"
}

### 사용자 등록 POST 요청 보내기
POST {{server}}/auth/login
Content-Type: application/json

{
    "email": "youngsang0124@gmail.com",
    "password": "Uusseerr1!"
}

### 게시글 조회 GET
GET {{server}}/board/671539441d0f72662215a968

### 게시글 수정 페이지 이동 GET 요청 보내기
GET {{server}}/board/671539441d0f72662215a968/edit
Accept: text/html

### 게시글 수정 PUT 요청 보내기
PUT {{server}}/board/671539441d0f72662215a968
Content-Type: application/json

{
  "title": "게시글 수정 테스트",
  "content": "this is a test of updating board"
}

### 게시글 삭제 DELETE 요청 보내기
DELETE {{server}}/board/671539441d0f72662215a966
Accept: application/json

### 댓글 등록 POST 요청 보내기
POST {{server}}/board/671539441d0f72662215a968/comments
Content-Type: application/json

{
  "content": "폼 미쳤다."
}

### 댓글 수정 PUT 요청 보내기
PUT {{server}}/board/671539441d0f72662215a968/comments/6717d510598e521c7140e96d
Content-Type: application/json

{
  "content": "기아 심판 매수해서 우승하네 ㄷㄷ"
}

### 댓글 삭제 DELETE 요청 보내기
DELETE {{server}}/board/671539441d0f72662215a968/comments/6718c4ae2e8e19211e38018f

### 답글 작성 POST 요청 보내기
POST {{server}}/board/671539441d0f72662215a968/comments/6717d510598e521c7140e96d/replies
Content-Type: application/json

{
  "content": "ㅆㅇㅈ ㅋㅋ"
}

### 답글 수정 PUT 요청 보내기
PUT {{server}}/board/671539441d0f72662215a968/comments/6717d510598e521c7140e96d/replies/6718d3366fa2ad751e77b89e
Content-Type: application/json

{
  "content": "응 아니야"
}

### 답글 삭제 DELETE 요청 보내기
DELETE {{server}}/board/671539441d0f72662215a968/comments/6717d510598e521c7140e96d/replies/6718e54f50975cebdad6d17e

### 회원가입 POST 요청 보내기
POST {{server}}/auth/signup
Content-Type: application/json

{
  "username": "test_user",
  "email": "youngsang0124@gmail.com",
  "password": "Uusseerr1!"
}